# Computational Environments Guide {-}

A software tool / program / package is at its core just code in a programming
language that usually performs a certain mathematical operation or function. In
bioinformatics specifically, many of these tools will perform various
statistical tests or data transformations or data manipulation.

## Don't reinvent the wheel! {-}
Many of the analyses in bioinformatics have already been implemented in a
variety of software packages maintained and released for general use.Whenever
possible, we should make efficient use of the tools available in order to solve
our problems, especially if someone has already solved it!

## Computational Environments {-}
The ability to install and use these different software tools will largely
depend upon three main factors related to the concept of computational
environments:

  1. Hardware / Operating System: Both the physical hardware and the operating
  system you are working with may affect the tools you are able to install and
  utilize. You likely have noticed that many programs and software you already
  use require you to choose specific versions tailored to an operating system or
  in some niche cases, hardware (i.e Apple silicon computers vs. intel-based,
  windows, linux).
  
  2. Dependencies: Software dependencies are other libraries or tools or code
  that the program in question *depend* on in order to work. Many software tools
  / packages reuse existing code and tools and build upon their functionality. 
  Certain tools may have hundreds of dependencies that enable them to function 
  and any changes in those dependencies may potentially change the behavior
  of the program and its operations.
  
  3. Versioning: Many commonly used software tools are regularly maintained and
  updated. In addition to bug fixes, newer versions often contain updated or
  novel features that expand the scope and functionality of the original tool.
  In many cases, these new versions may require newer versions of their
  dependencies and updates may unintentionally change the outputs from
  complicated algorithms or calculations.
  
  
## Why is this important? {-}
Science is built on the principle of reproducibility and
that results that reveal to us the ground "truth" should be able to be
reproduced by those performing the experiments and others. Bioinformatics
analyses are often complex, multi-faceted analysis pipelines that utilize a
combination of many different computational and mathematical approaches to
transform, manipulate and analyze data.

This presents a few challenges to reproducibility:

  1. We often have to make certain choices on how we manipulate or transform the
  data that will lead to radically different conclusions.
  
  2. Some of the algorithms and techniques we use are not fully deterministic and 
  may produce slightly different results when repeated. 
  
  3. Systemic changes in the underlying code of software tools or their
  dependencies may propagate across updates and versions, leading to slight
  differences in their behavior and output.
  
Below, we will discuss the various strategies we have for defining a computational
environment that will allow us to use these various tools and how we can ensure
that we (and others) can reproduce any results generated from them.

## Working locally {-}

One strategy for using and installing a tool is to simply download and install
it to your local desktop or laptop. You will need to download the appropriate
version for your system architecture and hope that the installation process
includes any necessary dependencies.

**When you might want to do this**:
- You want to very quickly analyze data or perform a task
- You want to troubleshoot or learn how a certain tool works

**Disadvantages**
- The installation is specific to your exact hardware and operating system. 
- Difficult to keep track of version and dependencies if you need to report or 
  publish them in a paper
- May not be reproducible outside of your specific environment
- Limited by your personal hardware specifications


## SCC Modules {-}

The SCC IT team has very conveniently pre-installed many different, commonly
used scientific packages and tools directly on the cluster. You may simply type
`module avail` when signed in to a terminal connected to the SCC to see the
available list of tools and their versions available. You may then use the
`module load name_of_tool` command, which will allow you to use the tool and all
of its functionalities. The module system will handle any dependencies and add
the tool to your path for your use.

**When you might want to do this**
- You want to very quickly analyze data or perform a task
- You want to troubleshoot or learn how a certain tool works
- The package isn't available through conda or docker

**Disadvantages**
- You are tied to only the versions pre-installed on the SCC (you may request updates but the SCC team is very busy)
- You are still tied to a specific system architecture (SCC)
- Difficult to keep track of version and dependencies if you need to report or 
  publish them in a paper
- May not be reproducible outside of your specific environment

## Using Conda on the SCC {-}






## Using containers on the SCC {-}

