---
---

# Project 3: RNAseq Individual Project {-}

This dataset consists of 6 samples: 4 WT and 4 KO derived from a human source.
Your workflow must perform a basic differential expression analysis comparing
between the conditions. You must perform QC at both the read and alignment level
as we have done during the class projects. 

**Your report must address the following topics/questions in writing:**

1. Briefly remark on the quality of the sequencing reads and the alignment
statistics, make sure to specifically mention the following:
    - Are there any concerning aspects of the quality control of your sequencing
      reads?
    - Are there any concerning aspects of the quality control related to
      alignment?
    - Based on all of your quality control, will you exclude any samples from
      further analysis?

2. After generating your counts matrix, perform either a PCA or produce a 
sample-to-sample distance plot as described in the DESeq2 vignette.
    - Briefly remark on the plot and what it indicates to you in terms of the 
      experiment
      
3. After performing DE analysis, choose an appropriate FDR threshold to subset
your DE results.
    - How many genes are significant at your chosen statistical threshold?
    
4. After performing FGSEA (GSEA) using a ranked list of all genes in the 
experiment and performing gene set enrichment using your list of statistically
significant DE genes, please answer the following questions:
    - How similar are the results from these two analyses? Are there any notable
      differences?
    - Do you expect there to be any differences? If so, why?
    - What do the results imply about potentional biological functions of the
      factor of interest?
    
**Deliverables**

1. Produce **either** a sample-to-sample distance plot from the counts matrix or
a PCA biplot

2. A CSV containing all of the results from your DE analysis

3. A histogram showing the distribution of log2FoldChanges of your DE genes

4. A volcano plot that distinguishes between significant and non-significant DE
genes as well as labels up- and downregulated genes
    - Label the top ten most significant genes with their associated gene name /
      gene symbol.

5. Perform a GSEA (FGSEA) analysis on all the genes discovered in the experiment
    - You may choose a ranking metric you feel is appropriate
    - You may use the C2 canonical pathways database or another of your choice
    - Create a single table / figure that reports the most interesting results
    
6. Use your list of DE genes at your chosen statistical threshold and perform a
basic enrichment analysis using a tool of your choice
    - You may use DAVID, enrichR, or other well-validated gene enrichment tools
    - Create a single table / figure that reports the most interesting results
